#define PAIR(a, b, c) [(a)] = (c), [(b)] = (c)

static const unsigned char char_to_codepoint[256] = {
    PAIR('`', '~', 9),
    PAIR('1', '!', 41),
    PAIR('2', '@', 42),
    PAIR('3', '#', 43),
    PAIR('4', '$', 44),
    PAIR('5', '%', 45),
    PAIR('6', '^', 46),
    PAIR('7', '&', 47),
    PAIR('8', '*', 40),
    PAIR('9', '(', 4),
    PAIR('0', ')', 5),
    PAIR('-', '_', 6),
    PAIR('=', '+', 3),

    PAIR('q', 'Q', 20),
    PAIR('w', 'W', 15),
    PAIR('e', 'E', 33),
    PAIR('r', 'R', 8),
    PAIR('t', 'T', 12),
    PAIR('y', 'Y', 28),
    PAIR('u', 'U', 24),
    PAIR('i', 'I', 10),
    PAIR('o', 'O', 38),
    PAIR('p', 'P', 16),
    PAIR('[', '{', 39),
    PAIR(']', '}', 0),
    ['\\'] = 7,
    ['|'] = 7,

    PAIR('a', 'A', 30),
    PAIR('s', 'S', 31),
    PAIR('d', 'D', 13),
    PAIR('f', 'F', 35),
    PAIR('g', 'G', 23),
    PAIR('h', 'H', 25),
    PAIR('j', 'J', 11),
    PAIR('k', 'K', 26),
    PAIR('l', 'L', 32),
    PAIR(';', ':', 21),
    PAIR('\'', '"', 17),

    PAIR('z', 'Z', 27),
    PAIR('x', 'X', 18),
    PAIR('c', 'C', 34),
    PAIR('v', 'V', 36),
    PAIR('b', 'B', 19),
    PAIR('n', 'N', 22),
    PAIR('m', 'M', 14),
    PAIR(',', '<', 37),
    PAIR('.', '>', 29),
    ['/'] = 1,
    ['?'] = 2,

    [' '] = 48,
};

#undef PAIR

#define KEY(k, c) [GLFW_KEY_##k] = (c)

static const int key_to_codepoint[256] = {
    KEY(GRAVE_ACCENT, 9),
    KEY(1, 41),
    KEY(2, 42),
    KEY(3, 43),
    KEY(4, 44),
    KEY(5, 45),
    KEY(6, 46),
    KEY(7, 47),
    KEY(8, 40),
    KEY(9, 4),
    KEY(0, 5),
    KEY(MINUS, 6),
    KEY(EQUAL, 3),

    KEY(Q, 20),
    KEY(W, 15),
    KEY(E, 33),
    KEY(R, 8),
    KEY(T, 12),
    KEY(Y, 28),
    KEY(U, 24),
    KEY(I, 10),
    KEY(O, 38),
    KEY(P, 16),
    KEY(LEFT_BRACKET, 39),
    KEY(RIGHT_BRACKET, 0),
    KEY(BACKSLASH, 7),

    KEY(A, 30),
    KEY(S, 31),
    KEY(D, 13),
    KEY(F, 35),
    KEY(G, 23),
    KEY(H, 25),
    KEY(J, 11),
    KEY(K, 26),
    KEY(L, 32),
    KEY(SEMICOLON, 21),
    KEY(APOSTROPHE, 17),

    KEY(Z, 27),
    KEY(X, 18),
    KEY(C, 34),
    KEY(V, 36),
    KEY(B, 19),
    KEY(N, 22),
    KEY(M, 14),
    KEY(COMMA, 37),
    KEY(PERIOD, 29),
    KEY(SLASH, 1),

    KEY(SPACE, 48),
};

static const int shift_key_to_codepoint[256] = {
    KEY(COMMA, 4),
    KEY(PERIOD, 5),
    KEY(SLASH, 2),
};

#undef KEY
