static const char* vertex_shader_source =
    "#version 100\n"
    "attribute vec2 position;\n"
    "attribute float glyph_codepoint;\n"
    "attribute float glyph_style;\n"
    "attribute vec2 glyph_coords;\n"
    "\n"
    "uniform vec2 viewport_size;\n"
    "uniform vec2 glyph_aspect;\n"
    "uniform mediump vec2 glyph_size;\n"
    "\n"
    "varying float codepoint;\n"
    "varying float style;\n"
    "varying vec2 coords;\n"
    "\n"
    "void main() {\n"
    "    codepoint = glyph_codepoint;\n"
    "    style = glyph_style;\n"
    "    coords = glyph_coords;\n"
    "    vec2 position_normal = ((position * glyph_size * glyph_aspect / viewport_size)\n"
    "        - vec2(0.5, 0.5)) * vec2(2.0, -2.0);\n"
    "    gl_Position = vec4(position_normal, 0.0, 1.0);\n"
    "}\n";

static const char* fragment_shader_source =
    "#version 100\n"
    "uniform mediump vec2 glyph_size;\n"
    "uniform mediump vec2 atlas_size;\n"
    "\n"
    "uniform sampler2D font_atlas;\n"
    "\n"
    "varying mediump vec2 coords;\n"
    "varying mediump float style;\n"
    "varying mediump float codepoint;\n"
    "\n"
    "void main() {\n"
    "    int cx = int(mod(codepoint, 16.0));\n"
    "    int cy = int(codepoint) / 16;\n"
    "    mediump vec2 relative_coords = coords + vec2(float(cx), float(cy));\n"
    "    mediump vec2 glyph_coords = glyph_size * relative_coords;\n"
    "    mediump vec2 texture_coords = glyph_coords / atlas_size;\n"
    "    mediump vec4 color = vec4(1.0, 1.0, 1.0, 1.0);\n"
    "    gl_FragColor = color * texture2D(font_atlas, texture_coords);\n"
    "}\n";
